services:
  agent:
    build:
      dockerfile: Dockerfile.agent.dev
    image: "agent"
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_RUN_PORT=8080
      - FLASK_APP=app.py
      - LANGCHAIN_PROJECT="Naptha_resume_agent"
