services:
  agent:
    build:
      dockerfile: Dockerfile.agent.prod
    image: "agent"
    ports:
      - "8000:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_RUN_PORT=8080
      - FLASK_APP=app.py
      - LANGCHAIN_PROJECT="Naptha_resume_agent"
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - ASHBY_API_KEY=${ASHBY_API_KEY}
      - ASHBY_WEBHOOK_SECRET=${ASHBY_WEBHOOK_SECRET}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - agent
    ports:
      - "80:80"
